services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: collabhub
      POSTGRES_PASSWORD: localdev
      POSTGRES_DB: collabhub
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U collabhub"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  piston_api:
    image: ghcr.io/engineer-man/piston
    container_name: piston_api
    ports:
      - "2000:2000"
    restart: unless-stopped
    privileged: true
    volumes:
      - ./piston_data:/piston/packages
    tmpfs:
      - /tmp

volumes:
  pgdata:
